export const data = [
  {
    id: 1235432,
    firstName: "Ben",
    lastName: "Doe",
    country: "USA",
    city: "Las Vegas",
    postalCode: 97035,
  },
  {
    id: 1235232,
    firstName: "John",
    lastName: "Larkin",
    country: "India",
    city: "Delhi",
    postalCode: 97035,
  },
  {
    id: 1635232,
    firstName: "Clark",
    lastName: "Kent",
    country: "Russia",
    city: "Moscow",
    postalCode: 97035,
  },
  {
    id: 7235232,
    firstName: "Billy",
    lastName: "Parker",
    country: "UAE",
    city: "Dubai",
    postalCode: 97035,
  },
  {
    id: 9235232,
    firstName: "Tony",
    lastName: "Stark",
    country: "New Zealand",
    city: "Auckland",
    postalCode: 97035,
  },
  {
    id: 92352321,
    firstName: "Adam",
    lastName: "Smasher",
    country: "Australia",
    city: "Melbourne",
    postalCode: 97035,
  },
];
